import json
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

from workspace_analyzer import AnalysisResult
from workspace_analyzer.cli import main

URDF = Path(__file__).parent / "fixtures/two_link.urdf"


def test_joint_cli_writes_loadable_result(tmp_path, capsys):
    output = tmp_path / "joint-result"
    result = main(
        [str(URDF), "--backend", "numpy", "--samples", "16", "--output", str(output)]
    )
    assert result.reachable is None
    assert AnalysisResult.load(output.with_suffix(".npz")).points.shape == (16, 3)
    assert "16 samples | 2 DoF | numpy:cpu" in capsys.readouterr().out


def test_cartesian_cli_uses_reference_joints(tmp_path, capsys):
    output = tmp_path / "cartesian.npz"
    result = main(
        [
            str(URDF),
            "--backend",
            "numpy",
            "--mode",
            "cartesian",
            "--bounds",
            "-2.5",
            "2.5",
            "-2.5",
            "2.5",
            "-0.000001",
            "0.000001",
            "--samples",
            "16",
            "--batch-size",
            "8",
            "--ik-restarts",
            "2",
            "--reference-joints",
            "0.1",
            "-0.1",
            "--output",
            str(output),
        ]
    )
    assert result.reachable.shape == (16,)
    assert result.metadata["reference_joints"] == [0.1, -0.1]
    assert "reachable:" in capsys.readouterr().out


def test_cartesian_cli_requires_bounds():
    with pytest.raises(SystemExit):
        main([str(URDF), "--backend", "numpy", "--mode", "cartesian"])


def test_console_entrypoint_exits_successfully_without_printing_result_object():
    # Match the sys.exit wrapper generated by the package installer.
    completed = subprocess.run(
        [
            sys.executable,
            "-c",
            "import sys; from workspace_analyzer.cli import entrypoint; "
            "sys.exit(entrypoint())",
            str(URDF),
            "--backend",
            "numpy",
            "--samples",
            "1",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0, completed.stderr
    assert completed.stderr == ""
    assert "1 samples | 2 DoF | numpy:cpu" in completed.stdout


@pytest.mark.parametrize(
    "args,message",
    [
        (["--samples", "0"], "num_samples"),
        (["--batch-size", "-1"], "batch_size"),
        (["--seed", "-1"], "seed"),
        (["--reference-joints", "nan", "0"], "finite"),
    ],
)
def test_cli_invalid_input_has_concise_error(args, message, capsys):
    with pytest.raises(SystemExit) as error:
        main([str(URDF), "--backend", "numpy", *args])
    assert error.value.code == 2
    stderr = capsys.readouterr().err
    assert message in stderr
    assert "Traceback" not in stderr


@pytest.mark.parametrize("extension", ["npy", "npz", "csv"])
def test_target_cli_writes_quality_report_and_result(extension, tmp_path, capsys):
    targets = np.array([[0, 0, 0], [0.95, 0, 0], [2, 0, 0]])
    path = tmp_path / f"targets.{extension}"
    if extension == "npy":
        np.save(path, targets)
    elif extension == "npz":
        np.savez(path, targets=targets, weights=[1, 2, 4], base_from_targets=np.eye(4))
    else:
        np.savetxt(path, targets, delimiter=",")
    report_path, result_path = tmp_path / "report.json", tmp_path / "result.npz"
    result = main(
        [
            str(URDF.with_name("cartesian_stage.urdf")),
            "--backend",
            "numpy",
            "--mode",
            "targets",
            "--targets",
            str(path),
            "--batch-size",
            "2",
            "--ik-restarts",
            "1",
            "--ik-rescue-restarts",
            "0",
            "--min-joint-limit-margin",
            ".1",
            "--report",
            str(report_path),
            "--output",
            str(result_path),
        ]
    )
    report = json.loads(report_path.read_text())["assessment"]
    assert report["ik_success_count"] == 2
    assert report["quality_pass_count"] == 1
    assert report["weighted_quality_pass_rate"] == pytest.approx(
        1 / (7 if extension == "npz" else 3)
    )
    restored = AnalysisResult.load(result_path)
    np.testing.assert_array_equal(
        restored.metrics["quality_pass"], result.metrics["quality_pass"]
    )
    assert "quality accepted: 33.3%" in capsys.readouterr().out


def test_full_pose_target_cli_preserves_orientations(tmp_path):
    path = tmp_path / "pose.npy"
    np.save(path, np.eye(4))
    result = main(
        [
            str(URDF.with_name("cartesian_stage.urdf")),
            "--backend",
            "numpy",
            "--mode",
            "targets",
            "--targets",
            str(path),
            "--full-pose",
            "--dexterity-task",
            "pose",
            "--require-full-rank",
            "--ik-restarts",
            "1",
            "--ik-rescue-restarts",
            "0",
        ]
    )
    assert result.reachable.all()
    assert not result.metrics["quality_pass"].any()
    np.testing.assert_array_equal(result.target_poses[0], np.eye(4))


def test_target_cli_requires_input_and_rejects_wrong_mode(capsys):
    for options, expected in [
        (["--mode", "targets"], "--targets is required"),
        (["--min-isotropy", ".1"], "require --mode targets"),
    ]:
        with pytest.raises(SystemExit) as error:
            main([str(URDF), *options])
        assert error.value.code == 2
        assert expected in capsys.readouterr().err


def test_target_cli_rejects_npz_without_targets(tmp_path, capsys):
    path = tmp_path / "missing.npz"
    np.savez(path, points=np.zeros((1, 3)))
    with pytest.raises(SystemExit) as error:
        main(
            [
                str(URDF),
                "--backend",
                "numpy",
                "--mode",
                "targets",
                "--targets",
                str(path),
            ]
        )
    assert error.value.code == 2
    assert "must contain a 'targets' array" in capsys.readouterr().err


def test_cli_uncompressed_cache_and_default_replay(tmp_path):
    from zipfile import ZIP_STORED, ZipFile

    args = [
        str(URDF),
        "--backend",
        "numpy",
        "--samples",
        "4",
        "--cache-dir",
        str(tmp_path),
    ]
    first = main([*args, "--cache-uncompressed"])
    with ZipFile(next(tmp_path.rglob("*.npz"))) as archive:
        assert all(info.compress_type == ZIP_STORED for info in archive.infolist())
    second = main(args)
    assert second.metadata["cache_hit"]
    np.testing.assert_array_equal(second.points, first.points)


def test_cli_uncompressed_requires_cache_directory():
    with pytest.raises(SystemExit) as error:
        main([str(URDF), "--cache-uncompressed"])
    assert error.value.code == 2
